name: wasm-pack test

on:
  workflow_call:
    inputs: 
      path:
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1
      - uses: baptiste0928/cargo-install@f204293d9709061b7bc1756fec3ec4e2cd57dec0 # v3
        with:
          crate: wasm-pack
          # renovate: datasource=crate depName=wasm-pack
          version: "0.14.0"
      - run: wasm-pack test --node ${{inputs.path}} --locked
