name: wasm-pack test

on:
  workflow_call:
    inputs: 
      path:
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions-rust-lang/setup-rust-toolchain@2b1f5e9b395427c92ee4e3331786ca3c37afe2d7 # v1
      - uses: baptiste0928/cargo-install@f204293d9709061b7bc1756fec3ec4e2cd57dec0 # v3
        with:
          crate: wasm-pack
          # renovate: datasource=crate depName=wasm-pack
          version: "0.14.0"
      - run: wasm-pack test --node ${{inputs.path}} --locked
