name: wasm-pack test

on:
  workflow_call:
    inputs: 
      path:
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: actions-rust-lang/setup-rust-toolchain@ecabd13d1c56bd1345c230e542e9144811ad706f # v2
      - uses: baptiste0928/cargo-install@8195d4f734a149db85385bb4102b42efcd373759 # v3
        with:
          crate: wasm-pack
          # renovate: datasource=crate depName=wasm-pack
          version: "0.15.0"
      - run: wasm-pack test --node ${{inputs.path}} --locked
